export const ACTION_TYPES = {
    SET_INSTRUCTIONS:'SET_INSTRUCTIONS',
    SET_TITLE:'SET_TITLE',
    SET_INGREDIENTS:'SET_INGREDIENTS',
    SET_COUNTER:'SET_COUNTER',
    SET_MACROS:'SET_MACRO',
    INCREMENT_COUNTER:'INCREMENT_COUNTER',
    ADD_INGREDIENT:'ADD_INGREDIENT',
    UPDATE_INGREDIENTS:'UPDATE_INGREDIENTS',
    UPDATE_QTY:'UPDATE_QTY',
    UPDATE_UNIT:'UPDATE_UNIT',
    DELETE_INGREDIENT:'DELETE_INGREDIENT'
}