export const ACTION_TYPES = {
    SET_RESULTS:'SET_RESULTS',
    SET_PAGE: 'SET_PAGE',
    SET_QUERY: 'SET_QUERY',
    SET_PREV_QUERY: 'SET_PREV_QUERY',
    SET_CRITERIA: 'setCriteSET_CRITERIAria',
    SET_PREV_CRITERIA: 'SET_PREV_CRITERIA'
}