export const ACTION_TYPES = {
    ADD_MEAL:'ADD_MEAL',
    REMOVE_MEAL:'REMOVE_MEAL',
    ADD_STATIC_MEAL:'ADD_STATIC_MEAL',
    SET_CARBS:'SET_CARBS',
    SET_PROTEIN:'SET_PROTEIN',
    SET_FAT:'SET_FAT',
    SET_CALORIES:'SET_CALORIES',
    SET_DAYS:'SET_DAYS',
    FORMAT_DAYS:'FORMAT_DAYS'
}